services:
  web-backend-sc2:
    image: web-backend-sc2
    container_name: web-backend-sc2
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    volumes: 
      - ./backend/src /app/src
      - ./backend/static /app/static


  web-frontend-sc2:
    image: web-frontend-sc2
    container_name: web-frontend-sc2
    depends_on:
      - web-backend-sc2
    build:
      context: ./frontend-svelte
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
    volumes: 
      - ./frontend-svelte/src /app/src
      - ./frontend-svelte/static /app/static