services:
  web-backend-sc2:
    image: web-backend-sc2
    container_name: web-backend-sc2
    build:
      network: host
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - ./backend/sc2_websocket_bridge:/app/sc2_websocket_bridge

  web-frontend-sc2:
    image: web-frontend-sc2
    container_name: web-frontend-sc2
    depends_on:
      - web-backend-sc2
    build:
      network: host
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes: 
      - ./frontend/src:/app/src:rw
      - ./frontend/static:/app/static:ro